### ISSUE TITLE
Cannot connect to on-prem zOS system using TLS

### ISSUE THREAD

**Issue by kristinochka** [IBM/micro3270#2]
I have an on-prem zOS system using self-signed certificate
Here's my launch command

`podman run -it icr.io/zmodstack/micro3270 host port`

I run the podman command and it brings up the emulator with a few menu options, but not the usual login screen. 
<img width="1125" alt="image" src="https://github.com/IBM/micro3270/assets/14590297/d102cb6d-ede4-4623-b38b-f355d140ec2e">

After 5 seconds the screen with menus goes away and it prints out the following error messages:
<img width="559" alt="image" src="https://github.com/IBM/micro3270/assets/14590297/6cadf23c-4dd7-4688-93bf-eec2060b88e4">

**Comment by ivandov** [comment]
Thank you for reporting this @kristinochka. 

I have released `v0.4.0` with proper support for SSL/TLS connectivity. Please try it out and let me know if there are any issues!

https://github.com/IBM/micro3270/releases/tag/0.4.0
